# Generated by Django 5.2.6 on 2025-10-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ferme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('proprietaire', models.CharField(max_length=100)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('capital_investi', models.PositiveIntegerField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('commentaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LotPoulets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lot', models.CharField(max_length=100)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_initial', models.PositiveIntegerField()),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('date_arrivee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField()),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarques (facultatif)')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dash_admin.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_aliment', models.CharField(max_length=100)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentations', to='dash_admin.lotpoulets')),
            ],
        ),
        migrations.CreateModel(
            name='Mortalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_mort', models.PositiveIntegerField()),
                ('date_mortalite', models.DateField()),
                ('cause', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalites', to='dash_admin.lotpoulets')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_production', models.CharField(choices=[('œufs', 'Œufs'), ('autre', 'Autre')], max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='dash_admin.lotpoulets')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('poulet', 'Poulet'), ('oeuf', 'Œuf')], max_length=10)),
                ('quantite_vendue', models.PositiveIntegerField(help_text="Nombre de poulets ou nombre d'œufs")),
                ('prix_unitaire', models.PositiveIntegerField()),
                ('montant_total', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('date_vente', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='dash_admin.lotpoulets')),
            ],
        ),
    ]
