# Generated by Django 5.2.6 on 2025-10-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalite',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_produit',
            field=models.CharField(max_length=10),
        ),
    ]
