# Generated by Django 5.2.6 on 2025-10-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0002_mortalite_types_alter_vente_type_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentation',
            name='types',
            field=models.CharField(default='poulet', max_length=100),
            preserve_default=False,
        ),
    ]
