# Generated by Django 5.2.6 on 2025-10-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0003_alimentation_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentation',
            name='types',
        ),
    ]
