# Generated by Django 5.2.6 on 2025-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0004_remove_alimentation_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('quantites', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
            ],
        ),
    ]
