# Generated by Django 5.2.6 on 2025-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0005_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
