# Generated by Django 5.2.6 on 2025-10-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0006_capital_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
