# Generated by Django 5.2.6 on 2025-10-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0007_capital_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='type_production',
        ),
    ]
