# Generated by Django 5.2.6 on 2025-12-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_admin', '0008_remove_production_type_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotpoulets',
            name='race',
        ),
    ]
